-- V1__create_campaigns_and_leads.sql
-- Create campaigns table
CREATE TABLE campaigns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    system_prompt TEXT,
    status VARCHAR(50) NOT NULL DEFAULT 'PAUSED',
    daily_limit INT NOT NULL DEFAULT 15,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_campaign_daily_limit CHECK (daily_limit >= 0),
    CONSTRAINT chk_campaign_status CHECK (status IN ('ACTIVE', 'PAUSED', 'COMPLETED'))
);

-- Create leads table
CREATE TABLE leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_id BIGINT NOT NULL,
    contact_identifier VARCHAR(255) NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
    last_contacted_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_leads_campaign FOREIGN KEY (campaign_id) REFERENCES campaigns (id) ON DELETE CASCADE,
    CONSTRAINT chk_lead_status CHECK (status IN ('PENDING', 'CONTACTED', 'RESPONDED', 'QUALIFIED', 'REJECTED', 'FAILED')),
    CONSTRAINT uq_campaign_lead UNIQUE (campaign_id, contact_identifier)
);

-- Performance Indexes
CREATE INDEX idx_campaigns_status ON campaigns(status);
CREATE INDEX idx_leads_campaign_id ON leads(campaign_id);
CREATE INDEX idx_leads_status ON leads(status);
