-- ==========================================
-- Flyway Versioned Migration: V2__create_dialogs_and_messages.sql
-- Description: Establishes dialogs and messages tables with proper relations, constraints, indexes, and documentation.
-- Owner: BARCAN-TAG-08 Data Engineering
-- Data Lineage:
--   - dialogs: Inbound Telegram webhook/listener -> DB dialogs
--   - messages: Telegram incoming events OR LLM responses OR Operator inputs -> DB messages
-- Consistent: Ensures integrity via FKs, CHECKs, NOT NULLs, and UNIQUE constraints.
-- Normalized: 3NF compliant.
-- Durable: Handled via transactional DDL.
-- ==========================================

CREATE TABLE dialogs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telegram_account_id BIGINT NOT NULL,
    telegram_chat_id BIGINT NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'AI_ACTIVE',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT uq_telegram_account_chat UNIQUE (telegram_account_id, telegram_chat_id),
    CONSTRAINT chk_dialog_status CHECK (status IN ('AI_ACTIVE', 'NEEDS_HUMAN', 'COMPLETED', 'SPAM'))
);

CREATE INDEX idx_dialogs_status ON dialogs(status);
CREATE INDEX idx_dialogs_telegram_chat ON dialogs(telegram_account_id, telegram_chat_id);

CREATE TABLE messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dialog_id BIGINT NOT NULL,
    sender_type VARCHAR(50) NOT NULL,
    text TEXT NOT NULL,
    telegram_message_id BIGINT,
    sent_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT fk_messages_dialog_id FOREIGN KEY (dialog_id) REFERENCES dialogs(id) ON DELETE CASCADE,
    CONSTRAINT chk_message_sender_type CHECK (sender_type IN ('AI', 'HUMAN', 'LEAD'))
);

CREATE INDEX idx_messages_dialog_id ON messages(dialog_id);
CREATE INDEX idx_messages_sent_at ON messages(sent_at);

-- Schema Documentation (Data Catalog)
COMMENT ON TABLE dialogs IS 'Owner: LeadGen App. Description: Stores active and historical conversation threads between physical TG accounts and target leads. Data Lineage: Inbound event listener / UI session setup.';
COMMENT ON COLUMN dialogs.id IS 'Primary key identifier for the dialog context.';
COMMENT ON COLUMN dialogs.telegram_account_id IS 'Reference ID of the managing automated Telegram account.';
COMMENT ON COLUMN dialogs.telegram_chat_id IS 'Unique identifier of the target recipient peer/chat in Telegram.';
COMMENT ON COLUMN dialogs.status IS 'Current operational state of the conversation, driving AI routing vs human agent takeover.';
COMMENT ON COLUMN dialogs.created_at IS 'Timestamp of dialog creation.';
COMMENT ON COLUMN dialogs.updated_at IS 'Timestamp of last update to dialog properties or status.';

COMMENT ON TABLE messages IS 'Owner: LeadGen App. Description: Holds sequential conversation messages for dialog history tracking and AI prompting. Data Lineage: Telegram Inbound Listener / AI Generator / CRM interface.';
COMMENT ON COLUMN messages.id IS 'Primary key identifier for the message.';
COMMENT ON COLUMN messages.dialog_id IS 'Foreign key reference linking the message back to its containing dialog conversation.';
COMMENT ON COLUMN messages.sender_type IS 'Role identifier of the message author (AI, HUMAN agent, or target LEAD).';
COMMENT ON COLUMN messages.text IS 'Actual textual content of the message.';
COMMENT ON COLUMN messages.telegram_message_id IS 'Remote message ID within the Telegram network, if dispatched and acknowledged.';
COMMENT ON COLUMN messages.sent_at IS 'Official timestamp when the message was sent or received via Telegram.';
COMMENT ON COLUMN messages.created_at IS 'Internal database record creation timestamp.';
